
@BaseUrl = app.swifter.ai

### 
// GET chatGateway
GET /api/chatGateway?merchantId=pH5vsgNnJQzP820kfDia&userId=134d492r81e8&textMessage=hi&appEnv=prod&agentEnv=prod HTTP/1.1
Host: {{BaseUrl}}
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*


### 